import { Inter } from "next/font/google";
import "./globals.css";
import { libre_caslon_display } from '@/app/ui/fonts';
import { libre_caslon_display_thin } from '@/app/ui/fonts';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div>
            <div className="h-40 w-48 bg-black flex items-center border-b-4 border-b-white padding-left-2">
              <p className={`text-white text-3xl pl-8 ${libre_caslon_display_thin.className}`}>
                Tally.ai
              </p>
            </div>
            <div className="absolute top-40 bottom-0 w-48 bg-black flex-col items-start">
              <p className="text-white pl-14 pt-8">
                Home
              </p>
              <p className="text-white pl-14 pt-3">
                Prospecting
              </p>
              <p className="text-white pl-14 pt-3">
                Settings
              </p>
              <p className="text-white pl-14 pt-3">
                Logout
              </p>
            </div>
          </div>
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
